"""Update assignment & enrollment column titles for consistency.

Revision ID: 212bededeacb
Revises: 55042cd5d016
Create Date: 2020-05-20 11:18:30.669632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212bededeacb'
down_revision = '55042cd5d016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('course_uid', sa.Integer(), nullable=False))
    op.add_column('assignment', sa.Column('instructor_uid', sa.Integer(), nullable=False))
    op.drop_constraint('assignment_instructor_id_fkey', 'assignment', type_='foreignkey')
    op.drop_constraint('assignment_course_id_fkey', 'assignment', type_='foreignkey')
    op.create_foreign_key(None, 'assignment', 'instructor', ['instructor_uid'], ['uid'])
    op.create_foreign_key(None, 'assignment', 'course', ['course_uid'], ['uid'], ondelete='CASCADE')
    op.drop_column('assignment', 'course_id')
    op.drop_column('assignment', 'instructor_id')
    op.add_column('enrollment', sa.Column('course_uid', sa.Integer(), nullable=False))
    op.add_column('enrollment', sa.Column('student_uid', sa.Integer(), nullable=False))
    op.drop_constraint('enrollment_student_id_fkey', 'enrollment', type_='foreignkey')
    op.drop_constraint('enrollment_course_id_fkey', 'enrollment', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment', 'course', ['course_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enrollment', 'student', ['student_uid'], ['uid'])
    op.drop_column('enrollment', 'course_id')
    op.drop_column('enrollment', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('enrollment', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.create_foreign_key('enrollment_course_id_fkey', 'enrollment', 'course', ['course_id'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key('enrollment_student_id_fkey', 'enrollment', 'student', ['student_id'], ['uid'])
    op.drop_column('enrollment', 'student_uid')
    op.drop_column('enrollment', 'course_uid')
    op.add_column('assignment', sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('assignment', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.create_foreign_key('assignment_course_id_fkey', 'assignment', 'course', ['course_id'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key('assignment_instructor_id_fkey', 'assignment', 'instructor', ['instructor_id'], ['uid'])
    op.drop_column('assignment', 'instructor_uid')
    op.drop_column('assignment', 'course_uid')
    # ### end Alembic commands ###
