"""Initial migration

Revision ID: 55042cd5d016
Revises: 
Create Date: 2020-05-20 09:38:25.977232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55042cd5d016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('days', sa.String(length=240), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('instructor',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=129), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('student',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assignment',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('enrollment',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    op.drop_table('assignment')
    op.drop_table('student')
    op.drop_table('instructor')
    op.drop_table('course')
    # ### end Alembic commands ###
