"""Add Grade table to database

Revision ID: 6c658d6ad87e
Revises: cfe9b7d9bca9
Create Date: 2020-07-17 18:15:05.873973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c658d6ad87e'
down_revision = 'cfe9b7d9bca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('student_uid', sa.Integer(), nullable=False),
    sa.Column('course_uid', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['course_uid'], ['course.uid'], ),
    sa.ForeignKeyConstraint(['student_uid'], ['student.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    # ### end Alembic commands ###
