"""Courses use start and end time instead of hour.

Revision ID: 899fb42e428c
Revises: 212bededeacb
Create Date: 2020-05-21 14:55:26.695957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899fb42e428c'
down_revision = '212bededeacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('end_time', sa.String(length=120), nullable=False))
    op.add_column('course', sa.Column('start_time', sa.String(length=120), nullable=False))
    op.drop_column('course', 'hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('course', 'start_time')
    op.drop_column('course', 'end_time')
    # ### end Alembic commands ###
